### ISSUE TITLE
Add CI environment for bulk Expression Atlas in GCP k8s cluster

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-bulk#157]
We need to create a CI pipeline for Bulk Expression Atlas, a similar one that we already have for Single Cell Expression Atlas.
This would help us to execute all our tests whenever we are working on a new feature / bug and making a Pull Request.

The list of tasks related to this EPIC:

- [x] [Config file for Jenkins that creates a POD for Bulk's CI pipeline](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/226)
- [x] [Define the Jenkinsfile for the execution of the pipeline for Bulk Expression Atlas CI](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/228)
- [x] [Create volume claims for Bulk Expression Atlas in GCP k8s cluster](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/7)
- [x] [Create and populate PostgreSQL DB for Bulk Expression Atlas CI](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/4)
- [x] [Create and populate Solr Cloud for Bulk Expression atlas CI](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/5)
- [ ] [Update README for the atlas-k8s-ci-environment repository](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/6)

Take [the scripts in `prepare-dev-environment` in bulk Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-bulk/pull/147) and add a set of K8s manifests to create a pre-populated SolrCloud cluster and experiment design volumes, etc. to run CI tests in bulk and `atlas-web-core`.

In the repository https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment create a directory that contains all the bulk YAML files and a `README.md` with instructions.

**Comment by ke4** [comment]
We started to add the Jenkins config files with @alfonsomunozpomer .
Here is the PR: #158

**Comment by ke4** [comment]
I started to add the yaml config files for `gxa-data` and `gxa-solrcloud` in  https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment repository.
Here is the PR: [[Chore] Create CI env in Jenkins for bulk Expression Atlas in GCP k8s cluster #3
](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/pull/3)
