### ISSUE TITLE
[EPIC] Create CI environment for Bulk Expression Atlas

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-bulk#225]
We need to create a CI pipeline for Bulk Expression Atlas, a similar one that we already have for Single Cell Expression Atlas.
This would help us to execute all our tests whenever we are working on a new feature / bug and we are creating a new branch for making a Pull Request.
We already started this activity with Alfonso in 2023, but could not finished as tasks with higher priority took over our time.

The list of tasks related to this EPIC:

- [ ] [Config file for Jenkins that creates a POD for Bulk's CI pipeline](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/226)
- [ ] [Define the Jenkinsfile for the execution of the pipeline for Bulk Expression Atlas CI](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/228)
- [ ] [Create volume claims for Bulk Expression Atlas in GCP k8s cluster](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/7)
- [ ] [Create and populate PostgreSQL DB for Bulk Expression Atlas CI](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/4)
- [ ] [Create and populate Solr Cloud for Bulk Expression atlas CI](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/5)
- [ ] [Update README for the atlas-k8s-ci-environment repository](https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment/issues/6)

Here is the previous task that we started earlier: [Add CI environment for bulk Expression Atlas in GCP k8s cluster](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/157). Have a look and you can cherry-pick from that older PR.

**Comment by ke4** [comment]
I am closing this as a duplicated ticket with this one: #157
